name: "Issue reviver"
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make run TARGETS="//tools/issue_reviver"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
